// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiFn6ANFTJwbY5BKHdOSmge1fzDOD_wBI',
    appId: '1:430002411880:android:8ccf02a0a07e794064dedd',
    messagingSenderId: '430002411880',
    projectId: 'residanatalgerseancesenl-ad38a',
    storageBucket: 'residanatalgerseancesenl-ad38a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6hNCqepF3A__WoWlnPW28tXMTqZkK1tI',
    appId: '1:430002411880:ios:ca449663959f8cc264dedd',
    messagingSenderId: '430002411880',
    projectId: 'residanatalgerseancesenl-ad38a',
    storageBucket: 'residanatalgerseancesenl-ad38a.appspot.com',
    iosClientId: '430002411880-vbj6efrlfhuo3rdsdimu4egem8i72doh.apps.googleusercontent.com',
    iosBundleId: 'com.abdelhamidmergh.residanatalgerseancesenlinge',
  );
}
